import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Emits .next/standalone with a minimal server plus only the traced
  // node_modules, so the runtime image needs no npm install.
  output: "standalone",

  // A type error should fail the build rather than ship a broken deploy.
  typescript: { ignoreBuildErrors: false },

  async headers() {
    return [
      {
        // The service worker decides what an offline tablet can do, so a
        // cached copy of it is a cached copy of the whole app's behaviour.
        // Kept uncacheable so a deploy can always replace it — see the
        // Cloudflare note in README.md, which has to be told the same thing.
        source: "/sw.js",
        headers: [
          {
            key: "Cache-Control",
            value: "no-cache, no-store, must-revalidate",
          },
          {
            key: "Content-Type",
            value: "application/javascript; charset=utf-8",
          },
          {
            // Lets the worker control every page rather than only /sw.js's
            // own directory. Redundant while it is served from the root, and
            // free insurance if it ever moves.
            key: "Service-Worker-Allowed",
            value: "/",
          },
        ],
      },
      {
        // Regenerated by scripts/sync-offline-data.mjs and served under a
        // stable URL, so it must be revalidated rather than assumed fresh.
        // The service worker serves it from cache and updates it behind the
        // reader, so revalidating costs nothing on the tablet.
        source: "/offline-data/:file*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=0, must-revalidate",
          },
        ],
      },
    ];
  },
};

export default nextConfig;
